import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1787589152081 implements MigrationInterface {
    name = 'InitSchema1787589152081'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."customs_documents_status_enum" AS ENUM('DRAFT', 'SUBMITTED', 'CLEARED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "customs_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "documentType" character varying NOT NULL, "referenceType" character varying, "referenceId" character varying, "status" "public"."customs_documents_status_enum" NOT NULL DEFAULT 'DRAFT', "fileUrl" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7b97dcfaee5fc3b7ef18d21e548" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customs_fees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "documentId" character varying NOT NULL, "description" character varying NOT NULL, "amount" numeric(12,2) NOT NULL, CONSTRAINT "PK_cf6cc0850153d4ffd11166553a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."destinations_type_enum" AS ENUM('BRANCH', 'EXTERNAL_CLIENT')`);
        await queryRunner.query(`CREATE TABLE "destinations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "type" "public"."destinations_type_enum" NOT NULL, "name" character varying NOT NULL, "address" character varying, "latitude" numeric(10,7), "longitude" numeric(10,7), "contactName" character varying, "contactPhone" character varying, "shippingChargeable" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_69c5e8db964dcb83d3a0640f3c7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "drivers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "userId" uuid, "fullName" character varying NOT NULL, "licenseNumber" character varying, "phone" character varying, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_92ab3fb69e566d3eb0cae896047" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."vehicles_status_enum" AS ENUM('AVAILABLE', 'ON_ROUTE', 'MAINTENANCE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "vehicles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "licensePlate" character varying NOT NULL, "type" character varying, "capacityKg" numeric(10,2), "capacityM3" numeric(10,3), "status" "public"."vehicles_status_enum" NOT NULL DEFAULT 'AVAILABLE', "gpsDeviceId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18d8646b59304dce4af3a9e35b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vehicle_maintenances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "vehicleId" uuid NOT NULL, "description" character varying NOT NULL, "cost" numeric(10,2), "performedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "nextDueAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_300f16840b4f0bd81303a594f79" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_plans_billingcycle_enum" AS ENUM('MONTHLY', 'ANNUAL')`);
        await queryRunner.query(`CREATE TABLE "subscription_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "priceUsd" numeric(10,2) NOT NULL, "billingCycle" "public"."subscription_plans_billingcycle_enum" NOT NULL DEFAULT 'MONTHLY', "features" jsonb NOT NULL, "trialDays" integer NOT NULL DEFAULT '14', "isActive" boolean NOT NULL DEFAULT true, "isVisible" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', "paypalPlanId" character varying, "mpPlanId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9ab8fe6918451ab3d0a4fb6bb0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "sku" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying, "category" character varying, "baseUnit" character varying NOT NULL DEFAULT 'UNIT', "weightKg" numeric(10,3) NOT NULL DEFAULT '0', "volumeM3" numeric(10,4) NOT NULL DEFAULT '0', "barcode" character varying, "requiresColdChain" boolean NOT NULL DEFAULT false, "hazardous" boolean NOT NULL DEFAULT false, "costPrice" numeric(12,2) NOT NULL DEFAULT '0', "minStockThreshold" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1b6c1ded9006ffc8e024caa715" ON "products"  ("tenantId", "sku") `);
        await queryRunner.query(`CREATE TABLE "product_packagings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "unit" character varying NOT NULL, "quantityInBaseUnit" integer NOT NULL, "isDefaultPurchaseUnit" boolean NOT NULL DEFAULT false, "isDefaultSaleUnit" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_580ff1a2497aaf893af6506b8c6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "warehouses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "name" character varying NOT NULL, "address" character varying, "latitude" numeric(10,7), "longitude" numeric(10,7), "usesLocationHierarchy" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_56ae21ee2432b2270b48867e4be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."routes_status_enum" AS ENUM('PLANNED', 'DISPATCHED', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "routes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "scheduledDate" date NOT NULL, "vehicleId" uuid, "driverId" uuid, "status" "public"."routes_status_enum" NOT NULL DEFAULT 'PLANNED', "dispatchedAt" TIMESTAMP WITH TIME ZONE, "completedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_76100511cdfa1d013c859f01d8b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."shipments_status_enum" AS ENUM('PREPARING', 'IN_TRANSIT', 'DELIVERED', 'INCIDENT')`);
        await queryRunner.query(`CREATE TABLE "shipments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "originWarehouseId" uuid NOT NULL, "destinationId" uuid NOT NULL, "routeId" uuid, "status" "public"."shipments_status_enum" NOT NULL DEFAULT 'PREPARING', "dispatchedAt" TIMESTAMP WITH TIME ZONE, "deliveredAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6deda4532ac542a93eab214b564" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shipment_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shipmentId" uuid NOT NULL, "productId" character varying NOT NULL, "requestedUnit" character varying NOT NULL, "requestedQuantityInUnit" integer NOT NULL, "quantityInBaseUnit" integer NOT NULL, CONSTRAINT "PK_5199504c6b5cdbd91701af3609b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "proof_of_deliveries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "shipmentId" uuid NOT NULL, "photoUrl" character varying, "signatureUrl" character varying, "receivedByName" character varying, "latitude" numeric(10,7), "longitude" numeric(10,7), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_4aacf6c148aa407e1519c92516" UNIQUE ("shipmentId"), CONSTRAINT "PK_f28cda93713eb76874d47b0f055" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shipment_costs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "shipmentId" uuid NOT NULL, "fuelCost" numeric(12,2) NOT NULL DEFAULT '0', "driverCost" numeric(12,2) NOT NULL DEFAULT '0', "otherCost" numeric(12,2) NOT NULL DEFAULT '0', "distanceKm" numeric(10,2), "totalCost" numeric(12,2) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_cb67668a50028ef09db4e991a4" UNIQUE ("shipmentId"), CONSTRAINT "PK_449278bd08ea3bdd036cf1b3a1a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shipment_charges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "shipmentId" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, "billingStatus" character varying NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_12feec31351a9d969764527e42" UNIQUE ("shipmentId"), CONSTRAINT "PK_cd4617f8997ece12fca385bb4a9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "onboardingCompleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2310ecc5cb8be427097154b18fc" UNIQUE ("slug"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('TRIAL', 'ACTIVE', 'PAST_DUE', 'SUSPENDED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "planId" uuid NOT NULL, "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'TRIAL', "trialEndsAt" TIMESTAMP WITH TIME ZONE, "currentPeriodEnd" TIMESTAMP WITH TIME ZONE, "cancelAtPeriodEnd" boolean NOT NULL DEFAULT false, "cancelledAt" TIMESTAMP WITH TIME ZONE, "pauseReason" character varying, "paypalSubscriptionId" character varying, "mpPreapprovalId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vehicle_positions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "vehicleId" uuid NOT NULL, "latitude" numeric(10,7) NOT NULL, "longitude" numeric(10,7) NOT NULL, "speedKmh" numeric(6,2), "heading" numeric(6,2), "recordedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_afcbb094766aaed9327e0eec07a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_75089a53e084d3d57460fb48a7" ON "vehicle_positions"  ("vehicleId", "recordedAt") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('ADMIN', 'FLEET_MANAGER', 'WAREHOUSE_OPERATOR', 'DRIVER')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "fullName" character varying NOT NULL, "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'WAREHOUSE_OPERATOR', "tokenVersion" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7346b08032078107fce81e014f" ON "users"  ("tenantId", "email") `);
        await queryRunner.query(`CREATE TYPE "public"."warehouse_locations_type_enum" AS ENUM('AISLE', 'SHELF', 'BIN')`);
        await queryRunner.query(`CREATE TABLE "warehouse_locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "warehouseId" uuid NOT NULL, "parentLocationId" uuid, "type" "public"."warehouse_locations_type_enum" NOT NULL, "code" character varying NOT NULL, "fullPath" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_03d900f32f1fcd299452d9eee7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_dc26dbb8b963505dcc3ede6a8a" ON "warehouse_locations"  ("warehouseId", "fullPath") `);
        await queryRunner.query(`CREATE TYPE "public"."stock_movements_type_enum" AS ENUM('IN', 'OUT', 'ADJUSTMENT', 'TRANSFER_OUT', 'TRANSFER_IN')`);
        await queryRunner.query(`CREATE TABLE "stock_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "productId" uuid NOT NULL, "warehouseId" uuid NOT NULL, "warehouseLocationId" uuid, "type" "public"."stock_movements_type_enum" NOT NULL, "quantityInBaseUnit" integer NOT NULL, "referenceType" character varying, "referenceId" character varying, "notes" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_57a26b190618550d8e65fb860e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_59b6b011376631d6a7f63f0507" ON "stock_movements"  ("tenantId", "productId", "warehouseId") `);
        await queryRunner.query(`CREATE TYPE "public"."warehouse_transfers_status_enum" AS ENUM('PENDING', 'IN_TRANSIT', 'RECEIVED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "warehouse_transfers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "originWarehouseId" uuid NOT NULL, "destinationWarehouseId" uuid NOT NULL, "status" "public"."warehouse_transfers_status_enum" NOT NULL DEFAULT 'PENDING', "routeId" uuid, "dispatchedAt" TIMESTAMP WITH TIME ZONE, "receivedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ad7cb2d7e9ae89bbb5f0444e92d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "warehouse_transfer_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "transferId" uuid NOT NULL, "productId" character varying NOT NULL, "quantityInBaseUnit" integer NOT NULL, CONSTRAINT "PK_d78759f74d17179e66454b738f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "vehicle_maintenances" ADD CONSTRAINT "FK_8bc8a2c47f79d9827d9b2371a5e" FOREIGN KEY ("vehicleId") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_packagings" ADD CONSTRAINT "FK_f4e728bf2c9187b10ba5fc76a3f" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "routes" ADD CONSTRAINT "FK_5e657840dfbba582b38696696e8" FOREIGN KEY ("vehicleId") REFERENCES "vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "routes" ADD CONSTRAINT "FK_2b32f218055ee12894887aa05cc" FOREIGN KEY ("driverId") REFERENCES "drivers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_a8382b6f5b8a01e6eabe8926572" FOREIGN KEY ("originWarehouseId") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_f258c006014981f7a1ef8fd963c" FOREIGN KEY ("destinationId") REFERENCES "destinations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_e33097d4c44c7247e285b362ae8" FOREIGN KEY ("routeId") REFERENCES "routes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipment_lines" ADD CONSTRAINT "FK_c2825d7f1dc60dec7fe4ef9d20b" FOREIGN KEY ("shipmentId") REFERENCES "shipments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proof_of_deliveries" ADD CONSTRAINT "FK_4aacf6c148aa407e1519c925163" FOREIGN KEY ("shipmentId") REFERENCES "shipments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipment_costs" ADD CONSTRAINT "FK_cb67668a50028ef09db4e991a4a" FOREIGN KEY ("shipmentId") REFERENCES "shipments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipment_charges" ADD CONSTRAINT "FK_12feec31351a9d969764527e427" FOREIGN KEY ("shipmentId") REFERENCES "shipments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_0c5fe8e5f9f4dd4a8c0134abc9c" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_7536cba909dd7584a4640cad7d5" FOREIGN KEY ("planId") REFERENCES "subscription_plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_positions" ADD CONSTRAINT "FK_0e46d1f61fb59461b0508e4cb8d" FOREIGN KEY ("vehicleId") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_c58f7e88c286e5e3478960a998b" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warehouse_locations" ADD CONSTRAINT "FK_ac9f8443edc269de2443e3bf25b" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warehouse_locations" ADD CONSTRAINT "FK_2c0f5e1cf6e5b565a2e4478ee29" FOREIGN KEY ("parentLocationId") REFERENCES "warehouse_locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_a3acb59db67e977be45e382fc56" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_2d118fa925e343f74b7dfe822ec" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_4f837d80244580eb737dafc5b71" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_locations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warehouse_transfers" ADD CONSTRAINT "FK_13f97024fdf323ca912ca45d067" FOREIGN KEY ("originWarehouseId") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warehouse_transfers" ADD CONSTRAINT "FK_cd712bafb3f22c260558c20ef63" FOREIGN KEY ("destinationWarehouseId") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warehouse_transfer_lines" ADD CONSTRAINT "FK_73e344577bdab3f2bad72f4ddb7" FOREIGN KEY ("transferId") REFERENCES "warehouse_transfers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "warehouse_transfer_lines" DROP CONSTRAINT "FK_73e344577bdab3f2bad72f4ddb7"`);
        await queryRunner.query(`ALTER TABLE "warehouse_transfers" DROP CONSTRAINT "FK_cd712bafb3f22c260558c20ef63"`);
        await queryRunner.query(`ALTER TABLE "warehouse_transfers" DROP CONSTRAINT "FK_13f97024fdf323ca912ca45d067"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_4f837d80244580eb737dafc5b71"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_2d118fa925e343f74b7dfe822ec"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_a3acb59db67e977be45e382fc56"`);
        await queryRunner.query(`ALTER TABLE "warehouse_locations" DROP CONSTRAINT "FK_2c0f5e1cf6e5b565a2e4478ee29"`);
        await queryRunner.query(`ALTER TABLE "warehouse_locations" DROP CONSTRAINT "FK_ac9f8443edc269de2443e3bf25b"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_c58f7e88c286e5e3478960a998b"`);
        await queryRunner.query(`ALTER TABLE "vehicle_positions" DROP CONSTRAINT "FK_0e46d1f61fb59461b0508e4cb8d"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_7536cba909dd7584a4640cad7d5"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_0c5fe8e5f9f4dd4a8c0134abc9c"`);
        await queryRunner.query(`ALTER TABLE "shipment_charges" DROP CONSTRAINT "FK_12feec31351a9d969764527e427"`);
        await queryRunner.query(`ALTER TABLE "shipment_costs" DROP CONSTRAINT "FK_cb67668a50028ef09db4e991a4a"`);
        await queryRunner.query(`ALTER TABLE "proof_of_deliveries" DROP CONSTRAINT "FK_4aacf6c148aa407e1519c925163"`);
        await queryRunner.query(`ALTER TABLE "shipment_lines" DROP CONSTRAINT "FK_c2825d7f1dc60dec7fe4ef9d20b"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_e33097d4c44c7247e285b362ae8"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_f258c006014981f7a1ef8fd963c"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_a8382b6f5b8a01e6eabe8926572"`);
        await queryRunner.query(`ALTER TABLE "routes" DROP CONSTRAINT "FK_2b32f218055ee12894887aa05cc"`);
        await queryRunner.query(`ALTER TABLE "routes" DROP CONSTRAINT "FK_5e657840dfbba582b38696696e8"`);
        await queryRunner.query(`ALTER TABLE "product_packagings" DROP CONSTRAINT "FK_f4e728bf2c9187b10ba5fc76a3f"`);
        await queryRunner.query(`ALTER TABLE "vehicle_maintenances" DROP CONSTRAINT "FK_8bc8a2c47f79d9827d9b2371a5e"`);
        await queryRunner.query(`DROP TABLE "warehouse_transfer_lines"`);
        await queryRunner.query(`DROP TABLE "warehouse_transfers"`);
        await queryRunner.query(`DROP TYPE "public"."warehouse_transfers_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59b6b011376631d6a7f63f0507"`);
        await queryRunner.query(`DROP TABLE "stock_movements"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movements_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc26dbb8b963505dcc3ede6a8a"`);
        await queryRunner.query(`DROP TABLE "warehouse_locations"`);
        await queryRunner.query(`DROP TYPE "public"."warehouse_locations_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7346b08032078107fce81e014f"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75089a53e084d3d57460fb48a7"`);
        await queryRunner.query(`DROP TABLE "vehicle_positions"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP TABLE "shipment_charges"`);
        await queryRunner.query(`DROP TABLE "shipment_costs"`);
        await queryRunner.query(`DROP TABLE "proof_of_deliveries"`);
        await queryRunner.query(`DROP TABLE "shipment_lines"`);
        await queryRunner.query(`DROP TABLE "shipments"`);
        await queryRunner.query(`DROP TYPE "public"."shipments_status_enum"`);
        await queryRunner.query(`DROP TABLE "routes"`);
        await queryRunner.query(`DROP TYPE "public"."routes_status_enum"`);
        await queryRunner.query(`DROP TABLE "warehouses"`);
        await queryRunner.query(`DROP TABLE "product_packagings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b6c1ded9006ffc8e024caa715"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "subscription_plans"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_plans_billingcycle_enum"`);
        await queryRunner.query(`DROP TABLE "vehicle_maintenances"`);
        await queryRunner.query(`DROP TABLE "vehicles"`);
        await queryRunner.query(`DROP TYPE "public"."vehicles_status_enum"`);
        await queryRunner.query(`DROP TABLE "drivers"`);
        await queryRunner.query(`DROP TABLE "destinations"`);
        await queryRunner.query(`DROP TYPE "public"."destinations_type_enum"`);
        await queryRunner.query(`DROP TABLE "customs_fees"`);
        await queryRunner.query(`DROP TABLE "customs_documents"`);
        await queryRunner.query(`DROP TYPE "public"."customs_documents_status_enum"`);
    }

}
