import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import {
  StockMovement,
  StockMovementType,
} from '../warehouses/stock-movement.entity';
import { Product } from './product.entity';
import { AddStockDto, AddStockType } from './dto/add-stock.dto';
import { UpdateStockMovementDto } from './dto/update-stock-movement.dto';

export interface StockBalanceRow {
  warehouseId: string;
  warehouseName: string;
  warehouseLocationId: string | null;
  locationFullPath: string | null;
  quantity: number;
}

@Injectable()
export class StockService {
  constructor(
    @InjectRepository(StockMovement)
    private readonly movementRepo: Repository<StockMovement>,
    @InjectRepository(Product)
    private readonly productRepo: Repository<Product>,
  ) {}

  private async assertProductExists(tenantId: string, productId: string) {
    const product = await this.productRepo.findOne({ where: { id: productId, tenantId } });
    if (!product) throw new NotFoundException('Producto no encontrado');
  }

  async getBalances(tenantId: string, productId: string): Promise<StockBalanceRow[]> {
    await this.assertProductExists(tenantId, productId);

    const rows = await this.movementRepo.manager.query(
      `SELECT
         sm."warehouseId" as "warehouseId",
         w."name" as "warehouseName",
         sm."warehouseLocationId" as "warehouseLocationId",
         wl."fullPath" as "locationFullPath",
         SUM(
           CASE
             WHEN sm."type" IN ('IN', 'TRANSFER_IN') THEN sm."quantityInBaseUnit"
             WHEN sm."type" IN ('OUT', 'TRANSFER_OUT') THEN -sm."quantityInBaseUnit"
             ELSE sm."quantityInBaseUnit"
           END
         )::int as "quantity"
       FROM stock_movements sm
       JOIN warehouses w ON w.id = sm."warehouseId"
       LEFT JOIN warehouse_locations wl ON wl.id = sm."warehouseLocationId"
       WHERE sm."tenantId" = $1 AND sm."productId" = $2
       GROUP BY sm."warehouseId", w."name", sm."warehouseLocationId", wl."fullPath"
       ORDER BY w."name" ASC, wl."fullPath" ASC NULLS FIRST`,
      [tenantId, productId],
    );

    return rows;
  }

  async getMovements(tenantId: string, productId: string) {
    await this.assertProductExists(tenantId, productId);

    return this.movementRepo.manager.query(
      `SELECT
         sm."id" as "id",
         sm."warehouseId" as "warehouseId",
         w."name" as "warehouseName",
         sm."warehouseLocationId" as "warehouseLocationId",
         wl."fullPath" as "locationFullPath",
         sm."type" as "type",
         sm."quantityInBaseUnit" as "quantityInBaseUnit",
         sm."referenceType" as "referenceType",
         sm."notes" as "notes",
         sm."createdAt" as "createdAt"
       FROM stock_movements sm
       JOIN warehouses w ON w.id = sm."warehouseId"
       LEFT JOIN warehouse_locations wl ON wl.id = sm."warehouseLocationId"
       WHERE sm."tenantId" = $1 AND sm."productId" = $2
       ORDER BY sm."createdAt" DESC`,
      [tenantId, productId],
    );
  }

  async addStock(tenantId: string, productId: string, dto: AddStockDto) {
    await this.assertProductExists(tenantId, productId);

    const type =
      dto.type === AddStockType.ADJUSTMENT
        ? StockMovementType.ADJUSTMENT
        : StockMovementType.IN;

    const movement = this.movementRepo.create({
      tenantId,
      productId,
      warehouseId: dto.warehouseId,
      warehouseLocationId: dto.warehouseLocationId ?? null,
      type,
      quantityInBaseUnit: dto.quantityInBaseUnit,
      referenceType: 'MANUAL',
      notes: dto.notes,
    });
    return this.movementRepo.save(movement);
  }

  // Only movements created manually from this screen can be edited/removed —
  // ones generated by dispatching a shipment or receiving a transfer are the
  // system's record of what actually happened and must stay immutable here.
  private async findEditableMovement(tenantId: string, productId: string, movementId: string) {
    const movement = await this.movementRepo.findOne({
      where: { id: movementId, tenantId, productId },
    });
    if (!movement) throw new NotFoundException('Movimiento no encontrado');
    if (movement.referenceType !== 'MANUAL') {
      throw new BadRequestException(
        'Este movimiento fue generado automáticamente por una operación (envío, transferencia) y no se puede editar acá.',
      );
    }
    return movement;
  }

  async updateMovement(
    tenantId: string,
    productId: string,
    movementId: string,
    dto: UpdateStockMovementDto,
  ) {
    const movement = await this.findEditableMovement(tenantId, productId, movementId);
    if (dto.quantityInBaseUnit !== undefined) {
      movement.quantityInBaseUnit = dto.quantityInBaseUnit;
    }
    if (dto.notes !== undefined) {
      movement.notes = dto.notes;
    }
    return this.movementRepo.save(movement);
  }

  async removeMovement(tenantId: string, productId: string, movementId: string) {
    const movement = await this.findEditableMovement(tenantId, productId, movementId);
    await this.movementRepo.remove(movement);
    return { id: movementId };
  }
}
