export enum UserRole {
  ADMIN = 'ADMIN',
  FLEET_MANAGER = 'FLEET_MANAGER',
  FLEET_SUPERVISOR = 'FLEET_SUPERVISOR',
  MECHANIC = 'MECHANIC',
  WAREHOUSE_OPERATOR = 'WAREHOUSE_OPERATOR',
  DRIVER = 'DRIVER',
}
